version: "3"

services:
  api:
    build: ./api
    image: api
    command: python app.py
    depends_on:
      - postgres
    environment:
      ENVIRONEMENT: "DEV"
      APPLICATION_HOST: "0.0.0.0"
      APPLICATION_PORT: 4000
      APPLICATION_POSTGRES_PW: postgrespasswd
      APPLICATION_POSTGRES_DB: chat_app
    ports:
      - "4000:4000"
    volumes:
      - ./api:/usr/src/app
  
  postgres:
    build: ./postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespasswd
      POSTGRES_DB: chat_app
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ~/.chat_app/pgdata:/var/lib/postgres/data/pgdata
  
  ui:
    build: ./ui
    image: ui
    command: npm run start
    environment:
      PORT: 3000
      CHAT_API_ENDPOINT: http://localhost:4000
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
